import type { Quiz, CustomType, HomeCategory, PaymentGateway, Coupon, CommerceSettings } from "./types";

// Payment gateways — all start DISABLED & DISCONNECTED. They only become
// "connected" after the admin enters real keys and tests the connection.
export const seedGateways: PaymentGateway[] = [
  { id: "paymob", name: "Paymob", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "fawry", name: "Fawry", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "meeza", name: "Meeza", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "vodafone", name: "Vodafone Cash", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "orange", name: "Orange Cash", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "etisalat", name: "Etisalat Cash", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "wepay", name: "WE Pay", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "instapay", name: "InstaPay", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "stripe", name: "Stripe (Visa/Mastercard/Apple/Google Pay)", region: "intl", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "paypal", name: "PayPal", region: "intl", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
];

export const seedCoupons: Coupon[] = [
  { id: "c-nurse10", code: "NURSE10", type: "percent", value: 10, maxUses: 100, used: 0, minPurchase: 0, expires: "2026-12-31", active: true, demo: true },
];

export const defaultCommerce: CommerceSettings = { currency: "EGP", taxPercent: 0, serviceFee: 0, country: "Egypt" };

// Default homepage category cards (editable & deletable from the admin panel).
export const seedHomeCategories: HomeCategory[] = [
  { id: "hc1", title: "المقالات", titleEn: "Articles", icon: "📝", description: "مقالات تعليمية في التمريض", descriptionEn: "Educational nursing articles", color: "from-sky-500 to-blue-500", order: 0, visible: true, link: "/category/articles", demo: true },
  { id: "hc2", title: "الملخصات", titleEn: "Summaries", icon: "📚", description: "ملخصات مركّزة للمواد", descriptionEn: "Focused subject summaries", color: "from-emerald-500 to-teal-500", order: 1, visible: true, link: "/category/summaries", demo: true },
  { id: "hc3", title: "الأدوية", titleEn: "Drugs", icon: "💊", description: "دليل الأدوية والجرعات", descriptionEn: "Drug guide & dosages", color: "from-violet-500 to-purple-500", order: 2, visible: true, link: "/drugs", demo: true },
  { id: "hc4", title: "المهارات", titleEn: "Skills", icon: "🩺", description: "مهارات سريرية عملية", descriptionEn: "Practical clinical skills", color: "from-amber-500 to-orange-500", order: 3, visible: true, link: "/category/skills", demo: true },
  { id: "hc5", title: "خطط الرعاية", titleEn: "Care Plans", icon: "📋", description: "خطط رعاية تمريضية", descriptionEn: "Nursing care plans", color: "from-rose-500 to-pink-500", order: 4, visible: true, link: "/category/careplans", demo: true },
  { id: "hc6", title: "الكتب وPDF", titleEn: "Books & PDFs", icon: "📖", description: "كتب وملفات قابلة للتحميل", descriptionEn: "Downloadable books & files", color: "from-cyan-500 to-sky-500", order: 5, visible: true, link: "/category/books", demo: true },
  { id: "hc7", title: "مكتبة ECG", titleEn: "ECG Library", icon: "🫀", description: "45 نمط تخطيط قلب مصنّف حسب الخطورة", descriptionEn: "45 ECG patterns classified by severity", color: "from-rose-600 to-slate-800", order: 6, visible: true, link: "/ecg", demo: false },
  { id: "hc8", title: "مكافحة العدوى", titleEn: "Infection Control", icon: "🦠", description: "نظافة اليدين والوقاية من العدوى", descriptionEn: "Hand hygiene & infection prevention", color: "from-red-500 to-orange-500", order: 7, visible: true, link: "/category/infection-control", demo: false },
  { id: "hc9", title: "الأدوات", titleEn: "Tools", icon: "🧮", description: "حاسبات طبية تساعدك في عملك", descriptionEn: "Medical calculators for your work", color: "from-indigo-500 to-purple-500", order: 8, visible: true, link: "/tools", demo: false },
  { id: "hc10", title: "المتجر", titleEn: "Store", icon: "🛍️", description: "كتب وكورسات واشتراكات مميزة", descriptionEn: "Books, courses & premium subscriptions", color: "from-emerald-500 to-teal-500", order: 9, visible: true, link: "/store", demo: false },
  { id: "hc11", title: "الاختبارات", titleEn: "Quizzes", icon: "📝", description: "اختبارات NCLEX تفاعلية لقياس مستواك", descriptionEn: "Interactive NCLEX-style quizzes to test your level", color: "from-fuchsia-500 to-pink-500", order: 10, visible: true, link: "/quizzes", demo: false },
  { id: "hc12", title: "العناية المركزة", titleEn: "ICU Nursing", icon: "🏥", description: "دليل شامل لتمريض العناية المركزة وبروتوكولاتها", descriptionEn: "A comprehensive guide to ICU nursing and its protocols", color: "from-red-600 to-rose-700", order: 11, visible: true, link: "/icu-nursing", demo: false },
];

// All seed content here is DEMO data (demo:true) so it can be deleted with one click.
export const seedQuizzes: Quiz[] = [
  {
    id: "q1",
    title: "NCLEX — أساسيات التمريض",
    titleEn: "NCLEX — Nursing Fundamentals",
    description: "اختبار تجريبي على غرار NCLEX يغطي أساسيات التمريض والعناية بالمريض.",
    descriptionEn: "An NCLEX-style practice quiz covering nursing fundamentals and patient care.",
    category: "NCLEX",
    categoryEn: "NCLEX",
    difficulty: "متوسط",
    timeLimit: 10,
    passScore: 60,
    status: "published",
    demo: true,
    questions: [
      {
        id: "q1a", text: "ما هي القيمة الطبيعية لمعدل ضربات القلب للبالغين؟",
        textEn: "What is the normal heart rate range for adults?",
        options: ["40-60 نبضة/دقيقة", "60-100 نبضة/دقيقة", "100-120 نبضة/دقيقة", "120-140 نبضة/دقيقة"],
        optionsEn: ["40-60 beats/min", "60-100 beats/min", "100-120 beats/min", "120-140 beats/min"],
        correct: 1, explanation: "المعدل الطبيعي لضربات القلب لدى البالغين هو 60-100 نبضة في الدقيقة.",
        explanationEn: "The normal heart rate for adults is 60-100 beats per minute.",
      },
      {
        id: "q1b", text: "أي مما يلي يعتبر أولوية عند تقييم مريض في حالة طوارئ؟",
        textEn: "Which of the following is a priority when assessing a patient in an emergency?",
        options: ["قياس درجة الحرارة", "تأمين مجرى الهواء (Airway)", "أخذ التاريخ المرضي", "قياس الوزن"],
        optionsEn: ["Measuring temperature", "Securing the airway", "Taking the medical history", "Measuring weight"],
        correct: 1, explanation: "وفق نهج ABC يأتي تأمين مجرى الهواء أولاً.",
        explanationEn: "According to the ABC approach, securing the airway comes first.",
      },
      {
        id: "q1c", text: "ما وضعية المريض المناسبة لتقليل ضيق التنفس؟",
        textEn: "Which patient position is appropriate to reduce shortness of breath?",
        options: ["وضعية الاستلقاء", "وضعية فاولر (Fowler)", "وضعية ترندلنبرغ", "الوضعية الجانبية"],
        optionsEn: ["Supine position", "Fowler's position", "Trendelenburg position", "Side-lying position"],
        correct: 1, explanation: "وضعية فاولر (الجلوس شبه المنتصب) تحسّن التنفس.",
        explanationEn: "Fowler's position (semi-upright sitting) improves breathing.",
      },
    ],
  },
  {
    id: "q2",
    title: "Prometric — علم الأدوية",
    titleEn: "Prometric — Pharmacology",
    description: "أسئلة على غرار امتحان بروميتريك في علم الأدوية والجرعات.",
    descriptionEn: "Prometric-style questions on pharmacology and dosing.",
    category: "Prometric",
    categoryEn: "Prometric",
    difficulty: "صعب",
    timeLimit: 8,
    passScore: 70,
    status: "published",
    demo: true,
    questions: [
      {
        id: "q2a", text: "أي فحص يُراقب مع مريض يتناول الوارفارين؟",
        textEn: "Which lab test is monitored for a patient taking warfarin?",
        options: ["مستوى السكر", "INR", "الهيموغلوبين", "البوتاسيوم"],
        optionsEn: ["Blood glucose level", "INR", "Hemoglobin", "Potassium"],
        correct: 1, explanation: "يُراقب INR لضبط جرعة الوارفارين.",
        explanationEn: "INR is monitored to adjust the warfarin dose.",
      },
      {
        id: "q2b", text: "الترياق (المضاد) لجرعة الهيبارين الزائدة هو؟",
        textEn: "The antidote for heparin overdose is?",
        options: ["فيتامين K", "بروتامين سلفات", "النالوكسون", "الأتروبين"],
        optionsEn: ["Vitamin K", "Protamine sulfate", "Naloxone", "Atropine"],
        correct: 1, explanation: "بروتامين سلفات هو الترياق للهيبارين.",
        explanationEn: "Protamine sulfate is the antidote for heparin.",
      },
    ],
  },
  {
    id: "q_med_calc",
    title: "حساب الجرعات الدوائية — تمرين تفاعلي",
    titleEn: "Medication Dose Calculations — Interactive Practice",
    description: "مسائل حسابية عملية: قواعد جرعة الطفل، معدل التنقيط والتسريب الوريدي، التخفيف، والجرعات المحسوبة على الوزن ومساحة سطح الجسم.",
    descriptionEn: "Practical calculation problems: pediatric dosing rules, IV drip and infusion rates, dilution, and weight- and body-surface-area-based dosing.",
    category: "حساب الجرعات",
    categoryEn: "Dose Calculation",
    difficulty: "متوسط",
    timeLimit: 20,
    passScore: 70,
    status: "published",
    demo: true,
    questions: [
      {
        id: "qmc1",
        text: "طفل عمره 6 سنوات، جرعة البالغ للدواء 500 مجم. احسبي جرعة الطفل باستخدام قاعدة Young (Age ÷ (Age+12) × جرعة البالغ).",
        textEn: "A 6-year-old child; the adult dose of the drug is 500 mg. Calculate the child's dose using Young's rule (Age ÷ (Age+12) × adult dose).",
        options: ["100 مجم", "167 مجم", "250 مجم", "300 مجم"],
        optionsEn: ["100 mg", "167 mg", "250 mg", "300 mg"],
        correct: 1, explanation: "6 ÷ (6+12) × 500 = 6/18 × 500 ≈ 167 مجم.",
        explanationEn: "6 ÷ (6+12) × 500 = 6/18 × 500 ≈ 167 mg.",
      },
      {
        id: "qmc2",
        text: "طفل وزنه 20 كجم، جرعة البالغ 300 مجم (بافتراض وزن بالغ قياسي 68 كجم). احسبي جرعة الطفل بقاعدة Clark (وزن الطفل ÷ وزن البالغ القياسي × جرعة البالغ).",
        textEn: "A child weighing 20 kg; the adult dose is 300 mg (assuming a standard adult weight of 68 kg). Calculate the child's dose using Clark's rule (child's weight ÷ standard adult weight × adult dose).",
        options: ["44 مجم", "88 مجم", "120 مجم", "150 مجم"],
        optionsEn: ["44 mg", "88 mg", "120 mg", "150 mg"],
        correct: 1, explanation: "20 ÷ 68 × 300 ≈ 88 مجم.",
        explanationEn: "20 ÷ 68 × 300 ≈ 88 mg.",
      },
      {
        id: "qmc3",
        text: "مريض وزنه 70 كجم، والجرعة الموصوفة 5 مجم/كجم. كم الجرعة الكلية المطلوبة؟",
        textEn: "A patient weighing 70 kg is prescribed 5 mg/kg. What is the total required dose?",
        options: ["70 مجم", "140 مجم", "350 مجم", "700 مجم"],
        optionsEn: ["70 mg", "140 mg", "350 mg", "700 mg"],
        correct: 2, explanation: "70 × 5 = 350 مجم.",
        explanationEn: "70 × 5 = 350 mg.",
      },
      {
        id: "qmc4",
        text: "لازم تُعطي 1000 مل محلول خلال 8 ساعات بمجموعة تسريب (drop factor) = 15 تنقيطة/مل. كم معدل التنقيط بالتنقيطة/دقيقة؟",
        textEn: "You must give 1000 mL of solution over 8 hours with an infusion set (drop factor) of 15 drops/mL. What is the drip rate in drops/minute?",
        options: ["21 تنقيطة/دقيقة", "31 تنقيطة/دقيقة", "42 تنقيطة/دقيقة", "63 تنقيطة/دقيقة"],
        optionsEn: ["21 drops/min", "31 drops/min", "42 drops/min", "63 drops/min"],
        correct: 1, explanation: "(1000 × 15) ÷ (8 × 60) = 15000 ÷ 480 ≈ 31 تنقيطة/دقيقة.",
        explanationEn: "(1000 × 15) ÷ (8 × 60) = 15000 ÷ 480 ≈ 31 drops/min.",
      },
      {
        id: "qmc5",
        text: "محلول 500 مل يُعطى خلال 4 ساعات عبر مضخة تسريب. كم معدل التسريب بالمل/ساعة؟",
        textEn: "A 500 mL solution is given over 4 hours via an infusion pump. What is the infusion rate in mL/hour?",
        options: ["100 مل/ساعة", "125 مل/ساعة", "150 مل/ساعة", "200 مل/ساعة"],
        optionsEn: ["100 mL/hr", "125 mL/hr", "150 mL/hr", "200 mL/hr"],
        correct: 1, explanation: "500 ÷ 4 = 125 مل/ساعة.",
        explanationEn: "500 ÷ 4 = 125 mL/hr.",
      },
      {
        id: "qmc6",
        text: "الطبيب طلب 0.25 مجم من دواء، والأمبولة المتاحة تركيزها 500 ميكروجرام/مل. كم مل ستسحبين؟",
        textEn: "The doctor ordered 0.25 mg of a drug, and the available ampule concentration is 500 micrograms/mL. How many mL will you draw up?",
        options: ["0.25 مل", "0.5 مل", "1 مل", "2 مل"],
        optionsEn: ["0.25 mL", "0.5 mL", "1 mL", "2 mL"],
        correct: 1, explanation: "0.25 مجم = 250 ميكروجرام؛ 250 ÷ 500 = 0.5 مل.",
        explanationEn: "0.25 mg = 250 micrograms; 250 ÷ 500 = 0.5 mL.",
      },
      {
        id: "qmc7",
        text: "أمبولة تركيزها 40 مجم/مل، ومطلوب تحضير 40 مل بتركيز 1 مجم/مل. كم مل من الأمبولة الأصلية تحتاجين (باستخدام C1V1=C2V2)؟",
        textEn: "An ampule has a concentration of 40 mg/mL, and you need to prepare 40 mL at a concentration of 1 mg/mL. How many mL of the original ampule do you need (using C1V1=C2V2)?",
        options: ["0.5 مل", "1 مل", "2 مل", "4 مل"],
        optionsEn: ["0.5 mL", "1 mL", "2 mL", "4 mL"],
        correct: 1, explanation: "40 × V1 = 1 × 40 → V1 = 1 مل.",
        explanationEn: "40 × V1 = 1 × 40 → V1 = 1 mL.",
      },
      {
        id: "qmc8",
        text: "المريض محتاج 24 وحدة إنسولين، والحقنة المدرّجة U-100 (1 مل = 100 وحدة). كم مل ستسحبين؟",
        textEn: "The patient needs 24 units of insulin, and the graduated syringe is U-100 (1 mL = 100 units). How many mL will you draw up?",
        options: ["0.12 مل", "0.24 مل", "0.4 مل", "2.4 مل"],
        optionsEn: ["0.12 mL", "0.24 mL", "0.4 mL", "2.4 mL"],
        correct: 1, explanation: "24 ÷ 100 = 0.24 مل.",
        explanationEn: "24 ÷ 100 = 0.24 mL.",
      },
      {
        id: "qmc9",
        text: "مساحة سطح جسم المريض 1.5 م²، والجرعة الموصوفة 100 مجم/م². كم الجرعة الكلية؟",
        textEn: "The patient's body surface area is 1.5 m², and the prescribed dose is 100 mg/m². What is the total dose?",
        options: ["100 مجم", "150 مجم", "175 مجم", "200 مجم"],
        optionsEn: ["100 mg", "150 mg", "175 mg", "200 mg"],
        correct: 1, explanation: "100 × 1.5 = 150 مجم.",
        explanationEn: "100 × 1.5 = 150 mg.",
      },
      {
        id: "qmc10",
        text: "الطبيب طلب إعطاء دواء دفعة وريدية (IV push) بمعدل 1 مل/دقيقة، والجرعة المطلوبة 4 مل. كم دقيقة سيستغرق الإعطاء الكامل؟",
        textEn: "The doctor ordered an IV push medication at a rate of 1 mL/minute, and the required dose is 4 mL. How many minutes will the full administration take?",
        options: ["1 دقيقة", "2 دقيقة", "4 دقائق", "8 دقائق"],
        optionsEn: ["1 minute", "2 minutes", "4 minutes", "8 minutes"],
        correct: 2, explanation: "4 مل ÷ 1 مل/دقيقة = 4 دقائق.",
        explanationEn: "4 mL ÷ 1 mL/minute = 4 minutes.",
      },
      {
        id: "qmc11",
        text: "بروتوكول الهيبارين يبدأ بجرعة تحميل 80 وحدة/كجم، لمريض وزنه 90 كجم. كم وحدة جرعة التحميل؟",
        textEn: "The heparin protocol starts with a loading dose of 80 units/kg, for a patient weighing 90 kg. How many units is the loading dose?",
        options: ["720 وحدة", "4500 وحدة", "7200 وحدة", "9000 وحدة"],
        optionsEn: ["720 units", "4500 units", "7200 units", "9000 units"],
        correct: 2, explanation: "80 × 90 = 7200 وحدة.",
        explanationEn: "80 × 90 = 7200 units.",
      },
      {
        id: "qmc12",
        text: "كم جرام دكستروز موجود في 500 مل من محلول دكستروز 5% (D5W)؟",
        textEn: "How many grams of dextrose are in 500 mL of 5% dextrose solution (D5W)?",
        options: ["5 جم", "25 جم", "50 جم", "100 جم"],
        optionsEn: ["5 g", "25 g", "50 g", "100 g"],
        correct: 1, explanation: "5% تعني 5 جم لكل 100 مل؛ 500 × 5 ÷ 100 = 25 جم.",
        explanationEn: "5% means 5 g per 100 mL; 500 × 5 ÷ 100 = 25 g.",
      },
      {
        id: "qmc13",
        text: "طفل وزنه 15 كجم، الحد الأقصى الآمن للدواء 40 مجم/كجم/يوم مقسومة كل 8 ساعات. الطبيب كتب 200 مجم كل 8 ساعات. هل الجرعة اليومية الكلية آمنة؟",
        textEn: "A child weighing 15 kg; the maximum safe dose of the drug is 40 mg/kg/day divided every 8 hours. The doctor prescribed 200 mg every 8 hours. Is the total daily dose safe?",
        options: ["آمنة ومطابقة تمامًا للحد الأقصى", "تتجاوز الحد الأقصى بالضعف", "أقل من اللازم بكثير", "تحتاج مضاعفة الجرعة"],
        optionsEn: ["Safe and exactly matches the maximum", "Exceeds the maximum by double", "Far below what is needed", "Needs the dose doubled"],
        correct: 0, explanation: "الحد الأقصى = 40 × 15 = 600 مجم/يوم. الجرعة الموصوفة = 200 × 3 = 600 مجم/يوم — مطابقة تمامًا للحد الأقصى.",
        explanationEn: "Maximum = 40 × 15 = 600 mg/day. Prescribed dose = 200 × 3 = 600 mg/day — exactly matches the maximum.",
      },
      {
        id: "qmc14",
        text: "معدل التسريب المطلوب 50 مل/ساعة، وحجم الكيس الكلي 1000 مل. كم ساعة سيستغرق تسريب الكيس بالكامل؟",
        textEn: "The required infusion rate is 50 mL/hour, and the total bag volume is 1000 mL. How many hours will it take to infuse the entire bag?",
        options: ["10 ساعات", "15 ساعة", "20 ساعة", "25 ساعة"],
        optionsEn: ["10 hours", "15 hours", "20 hours", "25 hours"],
        correct: 2, explanation: "1000 ÷ 50 = 20 ساعة.",
        explanationEn: "1000 ÷ 50 = 20 hours.",
      },
      {
        id: "qmc15",
        text: "أمبولة بودرة تحتوي 1 جم دواء، أُذيبت في 10 مل ماء للحقن. كم التركيز الناتج بالمجم/مل؟",
        textEn: "A powder ampule contains 1 g of drug, dissolved in 10 mL of water for injection. What is the resulting concentration in mg/mL?",
        options: ["10 مجم/مل", "50 مجم/مل", "100 مجم/مل", "1000 مجم/مل"],
        optionsEn: ["10 mg/mL", "50 mg/mL", "100 mg/mL", "1000 mg/mL"],
        correct: 2, explanation: "1 جم = 1000 مجم؛ 1000 ÷ 10 = 100 مجم/مل.",
        explanationEn: "1 g = 1000 mg; 1000 ÷ 10 = 100 mg/mL.",
      },
    ],
  },
  {
    id: "icu-shock-emergencies",
    title: "العناية المركزة — الصدمات والطوارئ الحرجة",
    titleEn: "ICU Nursing — Shock & Critical Emergencies",
    description: "أسئلة على الصدمة الإنتانية، الإنعاش القلبي الرئوي (ACLS)، الحساسية المفرطة، التسمم، والحروق.",
    descriptionEn: "Questions on septic shock, ACLS, anaphylaxis, poisoning, and burns.",
    category: "صدمات وطوارئ حرجة",
    categoryEn: "Shock & Critical Emergencies",
    difficulty: "صعب",
    timeLimit: 15,
    passScore: 70,
    status: "published",
    demo: false,
    questions: [
      {
        id: "icush1",
        text: "في الصدمة الإنتانية (Septic Shock)، ما الحد الأدنى لجرعة السوائل الوريدية الأولى وفق إرشادات Surviving Sepsis Campaign خلال أول 3 ساعات؟",
        textEn: "In septic shock, what is the minimum initial IV fluid bolus per the Surviving Sepsis Campaign within the first 3 hours?",
        options: ["10 مل/كجم", "20 مل/كجم", "30 مل/كجم", "60 مل/كجم"],
        optionsEn: ["10 mL/kg", "20 mL/kg", "30 mL/kg", "60 mL/kg"],
        correct: 2,
        explanation: "30 مل/كجم من المحلول الملحي البلوري (Crystalloid) هو الحد الأدنى الإلزامي خلال أول 3 ساعات من التعرف على الإنتان أو انخفاض الضغط.",
        explanationEn: "30 mL/kg of crystalloid is the mandatory minimum within the first 3 hours of recognizing sepsis or hypotension.",
      },
      {
        id: "icush2",
        text: "ما هو الدواء الرافع للضغط (Vasopressor) الأول المفضل في الصدمة الإنتانية؟",
        textEn: "What is the first-choice vasopressor in septic shock?",
        options: ["الدوبامين (Dopamine)", "النورإبينفرين (Norepinephrine)", "الإبينفرين (Epinephrine)", "الفينيليفرين (Phenylephrine)"],
        optionsEn: ["Dopamine", "Norepinephrine", "Epinephrine", "Phenylephrine"],
        correct: 1,
        explanation: "النورإبينفرين هو الرافع للضغط الأول المفضل في الصدمة الإنتانية حسب إرشادات Surviving Sepsis Campaign.",
        explanationEn: "Norepinephrine is the first-line vasopressor in septic shock per Surviving Sepsis Campaign guidelines.",
      },
      {
        id: "icush3",
        text: "مريض بصدمة قلبية (Cardiogenic Shock): أي وصف يطابق حالته الدورانية المتوقعة؟",
        textEn: "A patient in cardiogenic shock: which hemodynamic profile is expected?",
        options: [
          "نتاج قلبي منخفض ومقاومة وعائية مرتفعة",
          "نتاج قلبي مرتفع ومقاومة وعائية منخفضة",
          "نتاج قلبي طبيعي وضغط وريدي مركزي منخفض",
          "نتاج قلبي مرتفع وضغط دم مرتفع",
        ],
        optionsEn: [
          "Low cardiac output with high systemic vascular resistance",
          "High cardiac output with low systemic vascular resistance",
          "Normal cardiac output with low CVP",
          "High cardiac output with high blood pressure",
        ],
        correct: 0,
        explanation: "الصدمة القلبية سببها فشل ضخ القلب، فينخفض النتاج القلبي (Cardiac Output) وترتفع المقاومة الوعائية الجهازية (SVR) تعويضيًا — على عكس الصدمة الإنتانية (التوزيعية) التي يرتفع فيها النتاج القلبي مبدئيًا وتنخفض المقاومة.",
        explanationEn: "Cardiogenic shock results from pump failure: cardiac output falls and SVR rises compensatorily — the opposite of distributive (septic) shock, where CO is initially high and SVR is low.",
      },
      {
        id: "icush4",
        text: "في بروتوكول الإنعاش القلبي الرئوي المتقدم (ACLS) لتوقف القلب بنمط الرجفان البطيني (VF) المستمر، ما الدواء الأول الذي يُعطى؟",
        textEn: "In ACLS for persistent ventricular fibrillation (VF) cardiac arrest, what is the first drug given?",
        options: ["الأميودارون (Amiodarone) 300 مجم", "الإبينفرين (Epinephrine) 1 مجم", "الأتروبين (Atropine) 1 مجم", "بيكربونات الصوديوم"],
        optionsEn: ["Amiodarone 300 mg", "Epinephrine 1 mg", "Atropine 1 mg", "Sodium bicarbonate"],
        correct: 1,
        explanation: "الإبينفرين 1 مجم وريديًا يُعطى كل 3-5 دقائق بمجرد عدم استجابة أول صدمة كهربائية؛ الأميودارون يُضاف بعد الصدمة الثالثة إذا استمر VF/VT.",
        explanationEn: "Epinephrine 1 mg IV is given every 3-5 minutes once the first shock fails; amiodarone is added after the third shock if VF/VT persists.",
      },
      {
        id: "icush5",
        text: "ما مقدار الطاقة الموصى بها لأول صدمة كهربائية باستخدام جهاز صدمات ثنائي الطور (Biphasic Defibrillator) عند البالغين؟",
        textEn: "What is the recommended energy for the first shock with a biphasic defibrillator in adults?",
        options: ["50-100 جول", "120-200 جول", "300-360 جول", "400-450 جول"],
        optionsEn: ["50-100 J", "120-200 J", "300-360 J", "400-450 J"],
        correct: 1,
        explanation: "الأجهزة ثنائية الطور تستخدم عادة 120-200 جول حسب توصية الشركة المصنعة، مقابل 360 جول للأجهزة أحادية الطور القديمة.",
        explanationEn: "Biphasic devices typically use 120-200 J per manufacturer recommendation, versus 360 J for older monophasic devices.",
      },
      {
        id: "icush6",
        text: "ما العلاج الأول والأهم للحساسية المفرطة (Anaphylaxis)؟",
        textEn: "What is the first and most important treatment for anaphylaxis?",
        options: [
          "مضاد الهيستامين (Antihistamine) وريديًا",
          "الإبينفرين (Epinephrine) 0.3-0.5 مجم عضليًا في الفخذ الأمامي الوحشي",
          "الكورتيزون (Corticosteroid) وريديًا",
          "محلول ملحي وريدي فقط",
        ],
        optionsEn: [
          "IV antihistamine",
          "Epinephrine 0.3-0.5 mg IM in the anterolateral thigh",
          "IV corticosteroid",
          "IV saline alone",
        ],
        correct: 1,
        explanation: "الإبينفرين العضلي هو العلاج الأول المنقذ للحياة ويجب ألا يتأخر؛ مضادات الهيستامين والكورتيزون علاجات مساندة فقط.",
        explanationEn: "IM epinephrine is the life-saving first-line treatment and must not be delayed; antihistamines and corticosteroids are only adjunctive.",
      },
      {
        id: "icush7",
        text: "في أي حالة تسمم يُمنع إعطاء الفحم المنشّط (Activated Charcoal)؟",
        textEn: "In which poisoning scenario is activated charcoal contraindicated?",
        options: [
          "تناول جرعة زائدة من الباراسيتامول قبل ساعة",
          "ابتلاع مادة كاوية (Corrosive) أو انخفاض مستوى الوعي بدون حماية مجرى الهواء",
          "تناول جرعة زائدة من الأسبرين",
          "تناول أقراص منومة قبل نصف ساعة",
        ],
        optionsEn: [
          "Paracetamol overdose ingested one hour ago",
          "Ingestion of a corrosive substance, or decreased consciousness without airway protection",
          "Aspirin overdose",
          "Sedative pill overdose taken half an hour ago",
        ],
        correct: 1,
        explanation: "الفحم المنشّط ممنوع مع المواد الكاوية (خطر الثقب) ومع ضعف الوعي بدون تأمين مجرى الهواء (خطر الشفط الرئوي).",
        explanationEn: "Activated charcoal is contraindicated with caustic ingestions (perforation risk) and with decreased consciousness without a protected airway (aspiration risk).",
      },
      {
        id: "icush8",
        text: "حسب معادلة باركلاند (Parkland Formula) لإنعاش سوائل الحروق، كم يُعطى من الحجم الكلي المحسوب خلال أول 8 ساعات؟",
        textEn: "Per the Parkland formula for burn fluid resuscitation, what fraction of the total calculated volume is given in the first 8 hours?",
        options: ["ربع الكمية (25%)", "نصف الكمية (50%)", "ثلاثة أرباع الكمية (75%)", "الكمية كاملة (100%)"],
        optionsEn: ["A quarter (25%)", "Half (50%)", "Three-quarters (75%)", "The full amount (100%)"],
        correct: 1,
        explanation: "معادلة باركلاند: 4 مل × نسبة الحروق% × وزن الجسم(كجم)، يُعطى نصفها في أول 8 ساعات من وقت الإصابة (وليس من وقت الوصول)، والنصف الباقي خلال الـ16 ساعة التالية.",
        explanationEn: "Parkland formula: 4 mL × %TBSA × body weight(kg); half is given in the first 8 hours from the time of injury (not arrival), and the remaining half over the next 16 hours.",
      },
    ],
  },
  {
    id: "icu-respiratory-vent",
    title: "العناية المركزة — الجهاز التنفسي والتهوية الآلية",
    titleEn: "ICU Nursing — Respiratory & Mechanical Ventilation",
    description: "أسئلة على أوضاع التهوية الآلية، متلازمة الضائقة التنفسية (ARDS)، والوقاية من الالتهاب الرئوي المرتبط بالجهاز (VAP).",
    descriptionEn: "Questions on ventilator modes, ARDS, and VAP prevention.",
    category: "الجهاز التنفسي والتهوية",
    categoryEn: "Respiratory & Ventilation",
    difficulty: "صعب",
    timeLimit: 15,
    passScore: 70,
    status: "published",
    demo: false,
    questions: [
      {
        id: "icuresp1",
        text: "في وضع التهوية الآلية SIMV (Synchronized Intermittent Mandatory Ventilation)، ماذا يحدث بين الأنفاس الإجبارية المحددة؟",
        textEn: "In SIMV mode, what happens between the set mandatory breaths?",
        options: [
          "يتوقف الجهاز تمامًا عن العمل",
          "يسمح للمريض بالتنفس تلقائيًا بمجهوده الخاص",
          "يُعطى المريض أكسجين 100% باستمرار",
          "يُقفل مجرى الهواء الاصطناعي",
        ],
        optionsEn: [
          "The ventilator stops working entirely",
          "The patient is allowed spontaneous breaths at their own effort",
          "The patient continuously receives 100% oxygen",
          "The artificial airway is closed",
        ],
        correct: 1,
        explanation: "SIMV يجمع بين أنفاس إجبارية بمعدل وحجم محددين وأنفاس تلقائية يبذل فيها المريض مجهودًا، ما يجعله وضعًا شائعًا أثناء الفطام عن الجهاز.",
        explanationEn: "SIMV combines set-rate/volume mandatory breaths with patient-initiated spontaneous breaths, making it a common weaning mode.",
      },
      {
        id: "icuresp2",
        text: "ما الغرض الأساسي من الضغط الإيجابي في نهاية الزفير (PEEP)؟",
        textEn: "What is the primary purpose of Positive End-Expiratory Pressure (PEEP)?",
        options: [
          "زيادة معدل التنفس",
          "منع انخماص الحويصلات الهوائية وتحسين الأكسجة",
          "تقليل ضغط الدم",
          "تسريع الفطام عن الجهاز فورًا",
        ],
        optionsEn: [
          "Increasing respiratory rate",
          "Preventing alveolar collapse and improving oxygenation",
          "Lowering blood pressure",
          "Immediately speeding ventilator weaning",
        ],
        correct: 1,
        explanation: "الـ PEEP يحافظ على فتح الحويصلات الهوائية في نهاية الزفير فيمنع انخماصها (Atelectasis) ويحسّن التبادل الغازي.",
        explanationEn: "PEEP keeps alveoli open at end-expiration, preventing atelectasis and improving gas exchange.",
      },
      {
        id: "icuresp3",
        text: "حسب تعريف برلين (Berlin Definition) لمتلازمة الضائقة التنفسية الحادة (ARDS)، أي نسبة PaO2/FiO2 تشير إلى الدرجة الخفيفة (Mild)؟",
        textEn: "Per the Berlin Definition of ARDS, which PaO2/FiO2 ratio indicates mild ARDS?",
        options: ["أكثر من 300", "200-300", "100-200", "أقل من 100"],
        optionsEn: ["Above 300", "200-300", "100-200", "Below 100"],
        correct: 1,
        explanation: "تصنيف برلين: خفيف 200-300، متوسط 100-200، شديد أقل من 100، بشرط وجود PEEP لا يقل عن 5 سم ماء.",
        explanationEn: "Berlin classification: mild 200-300, moderate 100-200, severe below 100, all with PEEP ≥5 cmH2O.",
      },
      {
        id: "icuresp4",
        text: "من أهم عناصر حزمة الوقاية من الالتهاب الرئوي المرتبط بجهاز التنفس (VAP Bundle) رفع رأس السرير إلى:",
        textEn: "A key element of the VAP prevention bundle is elevating the head of the bed to:",
        options: ["0 درجة (مسطح تمامًا)", "10-15 درجة", "30-45 درجة", "90 درجة دائمًا"],
        optionsEn: ["0° (fully flat)", "10-15°", "30-45°", "Always 90°"],
        correct: 2,
        explanation: "رفع رأس السرير 30-45 درجة يقلل خطر شفط محتويات المعدة والإفرازات الفموية إلى الرئتين، وهو عنصر أساسي في حزمة VAP.",
        explanationEn: "Elevating the head of the bed 30-45° reduces the risk of aspirating gastric and oral secretions into the lungs — a core VAP bundle element.",
      },
      {
        id: "icuresp5",
        text: "مريض بتحليل غازات دم (ABG): pH 7.28، PaCO2 55. ما التفسير الأقرب؟",
        textEn: "A patient's ABG shows pH 7.28, PaCO2 55. What is the most likely interpretation?",
        options: ["حماض تنفسي (Respiratory Acidosis)", "قلاء تنفسي (Respiratory Alkalosis)", "حماض استقلابي (Metabolic Acidosis)", "قلاء استقلابي (Metabolic Alkalosis)"],
        optionsEn: ["Respiratory acidosis", "Respiratory alkalosis", "Metabolic acidosis", "Metabolic alkalosis"],
        correct: 0,
        explanation: "الـ pH أقل من 7.35 (حماض) مع PaCO2 مرتفع فوق 45 يشير إلى حماض تنفسي، غالبًا بسبب نقص التهوية (Hypoventilation).",
        explanationEn: "pH below 7.35 (acidemia) with an elevated PaCO2 above 45 indicates respiratory acidosis, usually from hypoventilation.",
      },
      {
        id: "icuresp6",
        text: "أي مؤشر يُستخدم لتقييم جاهزية المريض للفطام عن جهاز التنفس الصناعي؟",
        textEn: "Which index is used to assess readiness for ventilator weaning?",
        options: [
          "مقياس غلاسكو للوعي (GCS)",
          "مؤشر التنفس السريع الضحل (RSBI)",
          "مقياس برادن (Braden Scale)",
          "مقياس RASS للتسكين",
        ],
        optionsEn: ["Glasgow Coma Scale (GCS)", "Rapid Shallow Breathing Index (RSBI)", "Braden Scale", "RASS sedation scale"],
        correct: 1,
        explanation: "مؤشر RSBI = معدل التنفس ÷ حجم المد التنفسي(باللتر)؛ قيمة أقل من 105 تدل على احتمالية نجاح الفطام.",
        explanationEn: "RSBI = respiratory rate ÷ tidal volume (in liters); a value below 105 predicts a good chance of successful weaning.",
      },
      {
        id: "icuresp7",
        text: "قبل شفط إفرازات المريض عبر الأنبوب الرغامي (Endotracheal Suctioning)، ما الإجراء الضروري؟",
        textEn: "Before endotracheal suctioning, what is the essential step?",
        options: [
          "زيادة معدل السوائل الوريدية",
          "تزويد المريض بأكسجين 100% (Pre-oxygenation) لمدة 30-60 ثانية",
          "تخفيض تركيز الأكسجين إلى الحد الأدنى",
          "إعطاء جرعة إضافية من المهدئ فقط",
        ],
        optionsEn: [
          "Increasing IV fluid rate",
          "Pre-oxygenating with 100% O2 for 30-60 seconds",
          "Lowering the oxygen concentration to a minimum",
          "Just giving an extra sedative dose",
        ],
        correct: 1,
        explanation: "التزويد المسبق بالأكسجين يقلل خطر نقص الأكسجة أثناء الشفط، ويجب ألا تتجاوز مدة الشفط الواحد 10-15 ثانية.",
        explanationEn: "Pre-oxygenation reduces the risk of desaturation during suctioning; each suction pass should last no more than 10-15 seconds.",
      },
      {
        id: "icuresp8",
        text: "أي مما يلي عامل خطر رئيسي للإصابة بالالتهاب الرئوي المكتسب من المستشفى (Hospital-Acquired Pneumonia)؟",
        textEn: "Which of the following is a major risk factor for hospital-acquired pneumonia?",
        options: [
          "التهوية الآلية لأكثر من 48 ساعة",
          "المشي المبكر بعد العملية",
          "التغذية الفموية الطبيعية",
          "رفع رأس السرير باستمرار",
        ],
        optionsEn: [
          "Mechanical ventilation for more than 48 hours",
          "Early post-operative ambulation",
          "Normal oral feeding",
          "Continuously keeping the head of bed elevated",
        ],
        correct: 0,
        explanation: "التهوية الآلية لأكثر من 48 ساعة هي أهم عامل خطر لتطور الالتهاب الرئوي المرتبط بجهاز التنفس (VAP)، وهو نوع من الالتهاب الرئوي المكتسب من المستشفى.",
        explanationEn: "Mechanical ventilation beyond 48 hours is the top risk factor for VAP, a subtype of hospital-acquired pneumonia.",
      },
    ],
  },
  {
    id: "icu-cardiac-resus",
    title: "العناية المركزة — القلب والإنعاش",
    titleEn: "ICU Nursing — Cardiac & Resuscitation",
    description: "أسئلة على المتلازمة التاجية الحادة، الإنعاش القلبي الرئوي الأساسي، وPALS للأطفال.",
    descriptionEn: "Questions on acute coronary syndrome, high-quality CPR, and pediatric PALS.",
    category: "القلب والإنعاش",
    categoryEn: "Cardiac & Resuscitation",
    difficulty: "صعب",
    timeLimit: 15,
    passScore: 70,
    status: "published",
    demo: false,
    questions: [
      {
        id: "icucard1",
        text: "مريض وصل بألم صدر حاد يشتبه باحتشاء عضلة القلب (STEMI). ما أول فحص تشخيصي يجب إجراؤه؟",
        textEn: "A patient arrives with acute chest pain suspicious for STEMI. What is the first diagnostic test?",
        options: ["أنزيمات القلب (Troponin) فقط", "تخطيط كهربية القلب (12-lead ECG) خلال 10 دقائق", "أشعة صدر", "إيكو القلب"],
        optionsEn: ["Cardiac enzymes (troponin) alone", "12-lead ECG within 10 minutes", "Chest X-ray", "Echocardiogram"],
        correct: 1,
        explanation: "يجب إجراء تخطيط كهربية القلب خلال أول 10 دقائق من وصول أي مريض بألم صدر يوحي بمتلازمة تاجية حادة، لتحديد وجود STEMI من عدمه فورًا.",
        explanationEn: "A 12-lead ECG must be obtained within 10 minutes of arrival for any chest pain suggestive of acute coronary syndrome, to immediately identify STEMI.",
      },
      {
        id: "icucard2",
        text: "ما الهدف الزمني الموصى به من الباب إلى القسطرة (Door-to-Balloon Time) في احتشاء STEMI؟",
        textEn: "What is the recommended door-to-balloon time goal in STEMI?",
        options: ["أقل من 30 دقيقة", "أقل من 90 دقيقة", "أقل من 6 ساعات", "أقل من 24 ساعة"],
        optionsEn: ["Under 30 minutes", "Under 90 minutes", "Under 6 hours", "Under 24 hours"],
        correct: 1,
        explanation: "الهدف المعياري هو فتح الشريان بالقسطرة خلال 90 دقيقة من وصول المريض للمستشفى القادر على إجراء القسطرة.",
        explanationEn: "The standard goal is opening the artery via PCI within 90 minutes of arrival at a PCI-capable hospital.",
      },
      {
        id: "icucard3",
        text: "ما المعدل والعمق الموصى بهما للضغطات في الإنعاش القلبي الرئوي عالي الجودة (High-Quality CPR) للبالغين؟",
        textEn: "What is the recommended rate and depth for high-quality adult CPR compressions?",
        options: ["60-80/دقيقة بعمق 2-3 سم", "100-120/دقيقة بعمق 5-6 سم", "140-160/دقيقة بعمق 7-8 سم", "80-100/دقيقة بعمق 1-2 سم"],
        optionsEn: ["60-80/min at 2-3 cm depth", "100-120/min at 5-6 cm depth", "140-160/min at 7-8 cm depth", "80-100/min at 1-2 cm depth"],
        correct: 1,
        explanation: "المعدل الموصى به 100-120 ضغطة/دقيقة بعمق 5-6 سم مع السماح بارتداد كامل للصدر بين الضغطات وتقليل الانقطاعات.",
        explanationEn: "The recommended rate is 100-120 compressions/min at a depth of 5-6 cm, with full chest recoil between compressions and minimal interruptions.",
      },
      {
        id: "icucard4",
        text: "ما نسبة الضغط إلى التنفس (Compression:Ventilation) الموصى بها في إنعاش الأطفال (PALS) عندما يوجد منقذان اثنان؟",
        textEn: "What compression:ventilation ratio is recommended in PALS with two rescuers present?",
        options: ["30:2", "15:2", "5:1", "3:1"],
        optionsEn: ["30:2", "15:2", "5:1", "3:1"],
        correct: 1,
        explanation: "مع منقذين اثنين للأطفال والرضع، النسبة الموصى بها هي 15:2؛ أما مع منقذ واحد فتصبح 30:2 مثل البالغين.",
        explanationEn: "With two rescuers for children/infants, the recommended ratio is 15:2; with a single rescuer it becomes 30:2, as in adults.",
      },
      {
        id: "icucard5",
        text: "بعد عودة الدورة الدموية التلقائية (ROSC) عقب توقف القلب، ما أحد عناصر الرعاية الموصى بها؟",
        textEn: "After Return of Spontaneous Circulation (ROSC) following cardiac arrest, what is one recommended element of care?",
        options: [
          "رفع درجة حرارة الجسم فورًا",
          "إدارة الحرارة المستهدفة (Targeted Temperature Management)",
          "إيقاف كل السوائل الوريدية",
          "تجنب أي تخطيط كهربية قلب",
        ],
        optionsEn: [
          "Immediately raising body temperature",
          "Targeted Temperature Management",
          "Stopping all IV fluids",
          "Avoiding any ECG",
        ],
        correct: 1,
        explanation: "إدارة الحرارة المستهدفة (عادة 32-36 درجة مئوية لمدة 24 ساعة) تُستخدم لحماية الدماغ من الإصابة الثانوية بعد نقص الأكسجة الشامل أثناء توقف القلب.",
        explanationEn: "Targeted Temperature Management (typically 32-36°C for 24 hours) protects the brain from secondary injury after the global hypoxia of cardiac arrest.",
      },
      {
        id: "icucard6",
        text: "مريض بوذمة رئوية حادة (Acute Pulmonary Edema) بسبب قصور القلب. ما الوضعية الأنسب له؟",
        textEn: "A patient with acute pulmonary edema from heart failure: what is the most appropriate position?",
        options: ["الاستلقاء الكامل على الظهر", "وضعية فاولر العالية (High Fowler's) — الجلوس المستقيم", "الاستلقاء على البطن", "وضعية ترندلينبرغ"],
        optionsEn: ["Fully flat supine", "High Fowler's (upright sitting) position", "Prone position", "Trendelenburg position"],
        correct: 1,
        explanation: "الجلوس المستقيم (High Fowler's) يقلل العودة الوريدية للقلب ويسهل التنفس بتقليل الضغط على الحجاب الحاجز، وهو أساسي في إدارة الوذمة الرئوية الحادة.",
        explanationEn: "High Fowler's position reduces venous return and eases breathing by relieving diaphragmatic pressure — a cornerstone of acute pulmonary edema management.",
      },
      {
        id: "icucard7",
        text: "ما العرض الأكثر تحديدًا لاشتباه الانصمام الرئوي (Pulmonary Embolism) عند مريض بعد جراحة طويلة؟",
        textEn: "What finding most raises suspicion for pulmonary embolism after prolonged surgery?",
        options: [
          "ضيق تنفس مفاجئ مع ألم صدر جنبي وتسرع بالقلب",
          "صداع بسيط",
          "ألم بطن مزمن",
          "طفح جلدي منتشر",
        ],
        optionsEn: [
          "Sudden dyspnea with pleuritic chest pain and tachycardia",
          "Mild headache",
          "Chronic abdominal pain",
          "Widespread rash",
        ],
        correct: 0,
        explanation: "الضيق المفاجئ في التنفس مع ألم صدر جنبي وتسرع القلب، خصوصًا مع عوامل خطر مثل الجراحة الطويلة والجلوس لفترات، من أهم علامات الاشتباه بالانصمام الرئوي الناتج عن جلطة وريدية عميقة (DVT).",
        explanationEn: "Sudden dyspnea with pleuritic chest pain and tachycardia, especially with risk factors like prolonged surgery/immobility, strongly suggests pulmonary embolism from DVT.",
      },
      {
        id: "icucard8",
        text: "ما الفرق الأساسي بين أزمة ارتفاع الضغط الطارئة (Hypertensive Emergency) والملحة (Hypertensive Urgency)؟",
        textEn: "What is the key difference between hypertensive emergency and hypertensive urgency?",
        options: [
          "لا فرق، المصطلحان مترادفان",
          "وجود ضرر حاد في الأعضاء المستهدفة في حالة الطوارئ",
          "الملحة أخطر من الطارئة",
          "الطارئة لا تحتاج علاج فوري",
        ],
        optionsEn: [
          "No difference — the terms are synonymous",
          "Acute target-organ damage is present in the emergency",
          "Urgency is more dangerous than emergency",
          "The emergency needs no immediate treatment",
        ],
        correct: 1,
        explanation: "أزمة الضغط الطارئة تترافق مع ضرر حاد في عضو مستهدف (مخ، قلب، كلى) وتحتاج خفضًا فوريًا وريديًا للضغط؛ أما الملحة فارتفاع شديد في الضغط بدون ضرر عضوي حاد ويمكن علاجها بأدوية فموية.",
        explanationEn: "A hypertensive emergency involves acute target-organ damage (brain, heart, kidneys) and needs immediate IV blood-pressure lowering; urgency is severe hypertension without acute organ damage, manageable with oral agents.",
      },
    ],
  },
  {
    id: "icu-renal-fluids-metabolic",
    title: "العناية المركزة — الكلى والسوائل والاستقلاب",
    titleEn: "ICU Nursing — Renal, Fluids & Metabolic",
    description: "أسئلة على الحماض الكيتوني السكري (DKA)، الفشل الكلوي الحاد، اضطرابات الصوديوم والبوتاسيوم، والتغذية الوريدية.",
    descriptionEn: "Questions on DKA, acute kidney injury, sodium/potassium disorders, and TPN.",
    category: "الكلى والسوائل والاستقلاب",
    categoryEn: "Renal, Fluids & Metabolic",
    difficulty: "صعب",
    timeLimit: 15,
    passScore: 70,
    status: "published",
    demo: false,
    questions: [
      {
        id: "icurenal1",
        text: "في علاج الحماض الكيتوني السكري (DKA)، عند أي مستوى للغلوكوز في الدم يبدأ إضافة الدكستروز (Dextrose) لمحلول التسريب الوريدي؟",
        textEn: "In treating DKA, at what blood glucose level should dextrose be added to the IV infusion?",
        options: ["أقل من 500 مجم/دل", "أقل من 250 مجم/دل", "أقل من 100 مجم/دل", "أقل من 70 مجم/دل"],
        optionsEn: ["Below 500 mg/dL", "Below 250 mg/dL", "Below 100 mg/dL", "Below 70 mg/dL"],
        correct: 1,
        explanation: "عندما يصل الغلوكوز إلى أقل من 250 مجم/دل، يُضاف الدكستروز للمحلول الوريدي لمنع نقص السكر المفاجئ مع الاستمرار في تسريب الإنسولين حتى يُغلق الفجوة الكيتونية.",
        explanationEn: "Once glucose falls below 250 mg/dL, dextrose is added to the IV fluid to prevent hypoglycemia while insulin infusion continues until the ketosis/anion gap closes.",
      },
      {
        id: "icurenal2",
        text: "ما المحلول الوريدي الأول المستخدم في بدء علاج الحماض الكيتوني السكري (DKA)؟",
        textEn: "What is the first IV fluid used to start DKA treatment?",
        options: ["الدكستروز 5%", "المحلول الملحي الطبيعي 0.9% (Normal Saline)", "محلول ملحي مفرط التوتر 3%", "محلول لاكتات رينجر فقط"],
        optionsEn: ["5% Dextrose", "0.9% Normal Saline", "3% hypertonic saline", "Lactated Ringer's alone"],
        correct: 1,
        explanation: "المحلول الملحي الطبيعي 0.9% هو الخط الأول لتصحيح الجفاف الشديد المصاحب لـ DKA قبل البدء بالإنسولين.",
        explanationEn: "0.9% normal saline is the first-line fluid to correct the severe dehydration accompanying DKA, before starting insulin.",
      },
      {
        id: "icurenal3",
        text: "معايير RIFLE/AKIN لتصنيف الفشل الكلوي الحاد (AKI) تعتمد بشكل أساسي على:",
        textEn: "RIFLE/AKIN criteria for classifying AKI are based primarily on:",
        options: [
          "ارتفاع الكرياتينين وانخفاض إخراج البول",
          "مستوى الصوديوم في الدم فقط",
          "مستوى الهيموغلوبين",
          "درجة حرارة الجسم",
        ],
        optionsEn: [
          "Rise in creatinine and decreased urine output",
          "Blood sodium level alone",
          "Hemoglobin level",
          "Body temperature",
        ],
        correct: 0,
        explanation: "تصنيفات RIFLE وAKIN تعتمد على مقدار ارتفاع الكرياتينين من خط الأساس ومعدل إخراج البول خلال فترة زمنية محددة.",
        explanationEn: "RIFLE and AKIN staging are based on the rise in creatinine from baseline and urine output over a defined time period.",
      },
      {
        id: "icurenal4",
        text: "عند تصحيح نقص الصوديوم الحاد (Hyponatremia)، ما أقصى معدل تصحيح آمن لتجنب إزالة الميالين الجسري المركزي (Central Pontine Demyelination)؟",
        textEn: "When correcting hyponatremia, what is the maximum safe correction rate to avoid central pontine demyelination?",
        options: ["0.5-1 مللي مكافئ/لتر/ساعة (8-10 خلال 24 ساعة)", "5 مللي مكافئ/لتر/ساعة", "لا يوجد حد أقصى", "10 مللي مكافئ/لتر/ساعة"],
        optionsEn: ["0.5-1 mEq/L/hour (8-10 within 24 hours)", "5 mEq/L/hour", "No upper limit", "10 mEq/L/hour"],
        correct: 0,
        explanation: "التصحيح السريع الزائد عن 8-10 مللي مكافئ خلال 24 ساعة يعرّض المريض لخطر إزالة الميالين الجسري المركزي، وهي مضاعفة عصبية خطيرة قد تسبب شللًا رباعيًا.",
        explanationEn: "Correcting faster than 8-10 mEq within 24 hours risks central pontine demyelination — a serious neurological complication that can cause quadriplegia.",
      },
      {
        id: "icurenal5",
        text: "أي اضطراب كهارل (Electrolyte) هو الأخطر عند بدء التغذية الوريدية الكاملة (TPN) لمريض سوء تغذية شديد (خطر متلازمة إعادة التغذية)؟",
        textEn: "Which electrolyte disturbance is most dangerous when starting TPN in a severely malnourished patient (refeeding syndrome risk)?",
        options: ["ارتفاع الصوديوم", "نقص الفوسفات (Hypophosphatemia)", "ارتفاع الكالسيوم", "نقص اليوريا"],
        optionsEn: ["Hypernatremia", "Hypophosphatemia", "Hypercalcemia", "Low urea"],
        correct: 1,
        explanation: "متلازمة إعادة التغذية تسبب انتقالًا مفاجئًا للفوسفات والبوتاسيوم والمغنيسيوم داخل الخلايا، ونقص الفوسفات الحاد قد يؤدي لفشل تنفسي وقلبي؛ لذا تبدأ التغذية تدريجيًا مع مراقبة الكهارل عن كثب.",
        explanationEn: "Refeeding syndrome causes a sudden intracellular shift of phosphate, potassium, and magnesium; acute hypophosphatemia can cause respiratory and cardiac failure — feeding must start gradually with close electrolyte monitoring.",
      },
      {
        id: "icurenal6",
        text: "أي تغيير في تخطيط كهربية القلب (ECG) يُعد علامة مبكرة على ارتفاع البوتاسيوم (Hyperkalemia)؟",
        textEn: "Which ECG change is an early sign of hyperkalemia?",
        options: ["موجات T مسطحة", "موجات T مدببة (Peaked T waves)", "قطعة ST مرتفعة فقط", "موجة U بارزة"],
        optionsEn: ["Flattened T waves", "Peaked T waves", "ST elevation alone", "Prominent U wave"],
        correct: 1,
        explanation: "موجات T المدببة والضيقة هي أول علامة تخطيطية على ارتفاع البوتاسيوم، وقد تتطور لاحقًا إلى اتساع QRS وخطر اضطراب نظم قاتل إذا لم يُعالج.",
        explanationEn: "Tall, narrow, peaked T waves are the earliest ECG sign of hyperkalemia, which can progress to QRS widening and life-threatening arrhythmia if untreated.",
      },
      {
        id: "icurenal7",
        text: "ما الفرق الأساسي بين متلازمة فرط الأسمولية السكرية (HHS) والحماض الكيتوني السكري (DKA)؟",
        textEn: "What is the key difference between HHS and DKA?",
        options: [
          "HHS لا يصيب مرضى السكري أبدًا",
          "غياب أو قلة شديدة في الكيتونات وارتفاع أشد في الغلوكوز مع اضطراب وعي بارز في HHS",
          "DKA لا يسبب جفافًا",
          "HHS يُعالج بدون سوائل وريدية",
        ],
        optionsEn: [
          "HHS never occurs in diabetic patients",
          "Absent/minimal ketosis with much higher glucose and prominent altered mental status in HHS",
          "DKA does not cause dehydration",
          "HHS is treated without IV fluids",
        ],
        correct: 1,
        explanation: "HHS يتميز بغلوكوز أعلى بكثير (غالبًا فوق 600 مجم/دل)، وأسمولية مرتفعة جدًا، وكيتونات غائبة أو ضئيلة، مع اضطراب وعي بارز — بعكس DKA الذي تكون فيه الكيتونات والحماض الاستقلابي هما السمة المميزة.",
        explanationEn: "HHS features much higher glucose (often >600 mg/dL), very high osmolality, and absent/minimal ketosis, with prominent altered mental status — unlike DKA, where ketosis and metabolic acidosis are the defining features.",
      },
      {
        id: "icurenal8",
        text: "أي من المحاليل التالية يُصنف كمحلول ناقص التوتر (Hypotonic)؟",
        textEn: "Which of the following is classified as a hypotonic solution?",
        options: ["محلول ملحي طبيعي 0.9%", "محلول ملحي 0.45% (نصف طبيعي)", "دكستروز 5% في محلول ملحي طبيعي", "محلول ملحي مفرط التوتر 3%"],
        optionsEn: ["0.9% Normal Saline", "0.45% (half-normal) saline", "5% Dextrose in Normal Saline", "3% Hypertonic saline"],
        correct: 1,
        explanation: "المحلول الملحي 0.45% أسمولية أقل من البلازما فيُصنف ناقص التوتر ويستخدم لتعويض السوائل داخل الخلايا؛ بينما 0.9% متساوي التوتر تقريبًا، و3% مفرط التوتر.",
        explanationEn: "0.45% saline has a lower osmolality than plasma, making it hypotonic — used for intracellular fluid replacement; 0.9% is roughly isotonic, and 3% is hypertonic.",
      },
    ],
  },
  {
    id: "icu-fundamentals-procedures",
    title: "العناية المركزة — الأساسيات وإجراءات التمريض",
    titleEn: "ICU Nursing — Fundamentals & Nursing Procedures",
    description: "أسئلة على مقياس غلاسكو، مقاييس التسكين والهذيان، مقياس NEWS2، وحزم الوقاية من العدوى.",
    descriptionEn: "Questions on GCS, sedation/delirium scales, NEWS2, and infection-prevention bundles.",
    category: "أساسيات وإجراءات العناية المركزة",
    categoryEn: "ICU Fundamentals & Procedures",
    difficulty: "متوسط",
    timeLimit: 15,
    passScore: 70,
    status: "published",
    demo: false,
    questions: [
      {
        id: "icufund1",
        text: "أي درجة على مقياس غلاسكو للوعي (Glasgow Coma Scale) تشير إلى إصابة دماغية شديدة وتستدعي عادةً حماية مجرى الهواء؟",
        textEn: "Which GCS score indicates severe brain injury and usually requires airway protection?",
        options: ["15-13", "12-9", "8 أو أقل", "لا علاقة بين GCS وحماية مجرى الهواء"],
        optionsEn: ["15-13", "12-9", "8 or below", "GCS is unrelated to airway protection"],
        correct: 2,
        explanation: "قاعدة عملية شهيرة: \"GCS ≤ 8 = Intubate\" — درجة 8 أو أقل تعني إصابة شديدة وضعف قدرة المريض على حماية مجرى هوائه، فيحتاج غالبًا للتنبيب.",
        explanationEn: "A well-known rule: \"GCS ≤ 8 = Intubate\" — a score of 8 or below indicates severe injury and impaired airway protection, usually requiring intubation.",
      },
      {
        id: "icufund2",
        text: "ما الغرض من مقياس RASS (Richmond Agitation-Sedation Scale)؟",
        textEn: "What is the purpose of the RASS (Richmond Agitation-Sedation Scale)?",
        options: [
          "تقييم خطر تقرحات الفراش",
          "تقييم مستوى التسكين والهياج لدى مريض العناية المركزة",
          "تقييم وظائف الكلى",
          "تقييم خطر الجلطات الوريدية",
        ],
        optionsEn: [
          "Assessing pressure ulcer risk",
          "Assessing sedation/agitation level in ICU patients",
          "Assessing kidney function",
          "Assessing venous thromboembolism risk",
        ],
        correct: 1,
        explanation: "RASS مقياس من -5 (لا يستجيب) إلى +4 (هائج جدًا وخطر) يُستخدم لضبط جرعات المهدئات وتقييم عمق التسكين بشكل موضوعي ومتكرر.",
        explanationEn: "RASS ranges from -5 (unresponsive) to +4 (combative) and is used to titrate sedatives and objectively, repeatedly assess sedation depth.",
      },
      {
        id: "icufund3",
        text: "أداة CAM-ICU المستخدمة لتشخيص الهذيان (Delirium) تعتمد بشكل أساسي على وجود أي ميزة؟",
        textEn: "The CAM-ICU tool for diagnosing delirium primarily relies on which feature?",
        options: [
          "ارتفاع درجة الحرارة فقط",
          "بداية حادة و/أو مسار متذبذب في الحالة الذهنية",
          "انخفاض ضغط الدم",
          "وجود جرح جراحي",
        ],
        optionsEn: [
          "Fever alone",
          "Acute onset and/or fluctuating course of mental status",
          "Low blood pressure",
          "A surgical wound",
        ],
        correct: 1,
        explanation: "الميزة الأولى والأساسية في CAM-ICU هي البداية الحادة أو المسار المتذبذب لحالة الوعي، بالإضافة لتشتت الانتباه واضطراب مستوى الوعي أو التفكير غير المنظم.",
        explanationEn: "The first and essential CAM-ICU feature is acute onset or a fluctuating course of mental status, alongside inattention and either altered consciousness or disorganized thinking.",
      },
      {
        id: "icufund4",
        text: "من أهم عناصر حزمة إدخال القسطرة المركزية (Central Line Insertion Bundle) للوقاية من عدوى مجرى الدم (CLABSI)؟",
        textEn: "What is a key element of the central line insertion bundle to prevent CLABSI?",
        options: [
          "استخدام الكحول فقط بدون قفازات",
          "الاحتياطات المعقمة القصوى (Maximal Sterile Barrier Precautions)",
          "إدخال القسطرة بدون تعقيم الجلد",
          "تجنب اختيار موقع الإدخال بعناية",
        ],
        optionsEn: [
          "Using alcohol alone without gloves",
          "Maximal Sterile Barrier Precautions",
          "Inserting the line without skin antisepsis",
          "Not carefully selecting the insertion site",
        ],
        correct: 1,
        explanation: "الاحتياطات المعقمة القصوى (غطاء رأس، كمامة، رداء وقفازات معقمة، غطاء كامل للمريض) مع مطهر الكلورهكسيدين واختيار الموقع المناسب هي أساس حزمة منع CLABSI.",
        explanationEn: "Maximal sterile barrier precautions (cap, mask, sterile gown/gloves, full patient drape) with chlorhexidine antisepsis and careful site selection form the core of CLABSI prevention.",
      },
      {
        id: "icufund5",
        text: "على مقياس برادن (Braden Scale) لخطر تقرحات الفراش (المجموع من 6 إلى 23)، أي مجموع يشير إلى أعلى درجة خطورة؟",
        textEn: "On the Braden Scale for pressure ulcer risk (total 6-23), which total indicates the highest risk?",
        options: ["19-23", "15-18", "13-14", "9 أو أقل"],
        optionsEn: ["19-23", "15-18", "13-14", "9 or below"],
        correct: 3,
        explanation: "كلما قلّ مجموع مقياس برادن زاد الخطر: 19-23 لا خطر، 15-18 خطر خفيف، 13-14 خطر متوسط، 10-12 خطر مرتفع، و9 أو أقل خطر مرتفع جدًا.",
        explanationEn: "The lower the Braden total, the higher the risk: 19-23 no risk, 15-18 mild, 13-14 moderate, 10-12 high, and 9 or below very high risk.",
      },
      {
        id: "icufund6",
        text: "أي مجموع على مقياس NEWS2 (National Early Warning Score) يستدعي استجابة طوارئ فورية؟",
        textEn: "Which NEWS2 total score requires an immediate emergency response?",
        options: ["0", "1-4", "5-6", "7 أو أكثر"],
        optionsEn: ["0", "1-4", "5-6", "7 or more"],
        correct: 3,
        explanation: "مجموع 0 يعني مراقبة روتينية، 1-4 تقييم تمريضي، 5-6 استجابة عاجلة، أما 7 فأكثر فيستدعي استجابة طوارئ فورية غالبًا بمشاركة فريق الطوارئ الطبي.",
        explanationEn: "A total of 0 means routine monitoring, 1-4 nursing assessment, 5-6 urgent response, and 7 or more requires an immediate emergency response, usually involving a medical emergency team.",
      },
      {
        id: "icufund7",
        text: "قبل بدء التغذية عبر أنبوبة الرايل (NGT/Ryle's tube)، ما أكثر الطرق موثوقية للتأكد من مكانها الصحيح في المعدة؟",
        textEn: "Before starting feeding via an NGT (Ryle's tube), what is the most reliable way to confirm correct placement?",
        options: [
          "سماع صوت الهواء بالسماعة فوق المعدة فقط",
          "قياس درجة حموضة (pH) السائل المسحوب و/أو أشعة سينية تأكيدية",
          "ملاحظة لون الأنبوبة فقط",
          "سؤال المريض إن كان يشعر بالراحة",
        ],
        optionsEn: [
          "Auscultating an air bolus over the stomach alone",
          "Checking aspirate pH and/or a confirmatory X-ray",
          "Just observing the tube's color",
          "Simply asking if the patient feels comfortable",
        ],
        correct: 1,
        explanation: "سماع صوت الهواء وحده غير موثوق وقد يعطي نتيجة خاطئة إذا كانت الأنبوبة في الرئة؛ فحص حموضة السائل المسحوب (pH ≤5.5 عادة يؤكد الوضع بالمعدة) والأشعة السينية عند الشك هما الطريقتان الأكثر أمانًا.",
        explanationEn: "The auscultatory 'whoosh' test alone is unreliable and can be falsely reassuring even in lung placement; aspirate pH testing (≤5.5 usually confirms gastric placement) and X-ray when in doubt are the safest methods.",
      },
      {
        id: "icufund8",
        text: "في أداة التواصل SBAR المستخدمة عند تسليم المريض (Handover)، ماذا يمثل الحرف الثالث R؟",
        textEn: "In the SBAR communication tool used at patient handover, what does the letter R stand for?",
        options: ["Recovery (التعافي)", "Recommendation (التوصية)", "Records (السجلات)", "Response (الاستجابة)"],
        optionsEn: ["Recovery", "Recommendation", "Records", "Response"],
        correct: 1,
        explanation: "SBAR تعني: الحالة (Situation)، الخلفية (Background)، التقييم (Assessment)، والتوصية (Recommendation) — إطار منظم يقلل ضياع المعلومات الحرجة أثناء التسليم بين الفرق الطبية.",
        explanationEn: "SBAR stands for Situation, Background, Assessment, and Recommendation — a structured framework that reduces critical information loss during handover between care teams.",
      },
    ],
  },
];

export const seedCustomTypes: CustomType[] = [
  {
    id: "ct1",
    name: "دراسات حالة",
    slug: "case-studies",
    icon: "🏥",
    demo: true,
    fields: [
      { key: "patient", label: "بيانات المريض", type: "text" },
      { key: "presentation", label: "العرض السريري", type: "textarea" },
      { key: "management", label: "الخطة العلاجية", type: "textarea" },
    ],
  },
];
