import type { Quiz, CustomType, HomeCategory, PaymentGateway, Coupon, CommerceSettings } from "./types";

// Payment gateways — all start DISABLED & DISCONNECTED. They only become
// "connected" after the admin enters real keys and tests the connection.
export const seedGateways: PaymentGateway[] = [
  { id: "paymob", name: "Paymob", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "fawry", name: "Fawry", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "meeza", name: "Meeza", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "vodafone", name: "Vodafone Cash", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "orange", name: "Orange Cash", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "etisalat", name: "Etisalat Cash", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "wepay", name: "WE Pay", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "instapay", name: "InstaPay", region: "eg", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "stripe", name: "Stripe (Visa/Mastercard/Apple/Google Pay)", region: "intl", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
  { id: "paypal", name: "PayPal", region: "intl", enabled: false, mode: "sandbox", apiKey: "", secretKey: "", connected: false },
];

export const seedCoupons: Coupon[] = [
  { id: "c-nurse10", code: "NURSE10", type: "percent", value: 10, maxUses: 100, used: 0, minPurchase: 0, expires: "2026-12-31", active: true, demo: true },
];

export const defaultCommerce: CommerceSettings = { currency: "EGP", taxPercent: 0, serviceFee: 0, country: "Egypt" };

// Default homepage category cards (editable & deletable from the admin panel).
export const seedHomeCategories: HomeCategory[] = [
  { id: "hc1", title: "المقالات", titleEn: "Articles", icon: "📝", description: "مقالات تعليمية في التمريض", descriptionEn: "Educational nursing articles", color: "from-sky-500 to-blue-500", order: 0, visible: true, link: "/category/articles", demo: true },
  { id: "hc2", title: "الملخصات", titleEn: "Summaries", icon: "📚", description: "ملخصات مركّزة للمواد", descriptionEn: "Focused subject summaries", color: "from-emerald-500 to-teal-500", order: 1, visible: true, link: "/category/summaries", demo: true },
  { id: "hc3", title: "الأدوية", titleEn: "Drugs", icon: "💊", description: "دليل الأدوية والجرعات", descriptionEn: "Drug guide & dosages", color: "from-violet-500 to-purple-500", order: 2, visible: true, link: "/drugs", demo: true },
  { id: "hc4", title: "المهارات", titleEn: "Skills", icon: "🩺", description: "مهارات سريرية عملية", descriptionEn: "Practical clinical skills", color: "from-amber-500 to-orange-500", order: 3, visible: true, link: "/category/skills", demo: true },
  { id: "hc5", title: "خطط الرعاية", titleEn: "Care Plans", icon: "📋", description: "خطط رعاية تمريضية", descriptionEn: "Nursing care plans", color: "from-rose-500 to-pink-500", order: 4, visible: true, link: "/category/careplans", demo: true },
  { id: "hc6", title: "الكتب وPDF", titleEn: "Books & PDFs", icon: "📖", description: "كتب وملفات قابلة للتحميل", descriptionEn: "Downloadable books & files", color: "from-cyan-500 to-sky-500", order: 5, visible: true, link: "/category/books", demo: true },
  { id: "hc7", title: "مكتبة ECG", titleEn: "ECG Library", icon: "🫀", description: "45 نمط تخطيط قلب مصنّف حسب الخطورة", descriptionEn: "45 ECG patterns classified by severity", color: "from-rose-600 to-slate-800", order: 6, visible: true, link: "/ecg", demo: false },
  { id: "hc8", title: "مكافحة العدوى", titleEn: "Infection Control", icon: "🦠", description: "نظافة اليدين والوقاية من العدوى", descriptionEn: "Hand hygiene & infection prevention", color: "from-red-500 to-orange-500", order: 7, visible: true, link: "/category/infection-control", demo: false },
  { id: "hc9", title: "الأدوات", titleEn: "Tools", icon: "🧮", description: "حاسبات طبية تساعدك في عملك", descriptionEn: "Medical calculators for your work", color: "from-indigo-500 to-purple-500", order: 8, visible: true, link: "/tools", demo: false },
  { id: "hc10", title: "المتجر", titleEn: "Store", icon: "🛍️", description: "كتب وكورسات واشتراكات مميزة", descriptionEn: "Books, courses & premium subscriptions", color: "from-emerald-500 to-teal-500", order: 9, visible: true, link: "/store", demo: false },
];

// All seed content here is DEMO data (demo:true) so it can be deleted with one click.
export const seedQuizzes: Quiz[] = [
  {
    id: "q1",
    title: "NCLEX — أساسيات التمريض",
    titleEn: "NCLEX — Nursing Fundamentals",
    description: "اختبار تجريبي على غرار NCLEX يغطي أساسيات التمريض والعناية بالمريض.",
    descriptionEn: "An NCLEX-style practice quiz covering nursing fundamentals and patient care.",
    category: "NCLEX",
    categoryEn: "NCLEX",
    difficulty: "متوسط",
    timeLimit: 10,
    passScore: 60,
    status: "published",
    demo: true,
    questions: [
      {
        id: "q1a", text: "ما هي القيمة الطبيعية لمعدل ضربات القلب للبالغين؟",
        textEn: "What is the normal heart rate range for adults?",
        options: ["40-60 نبضة/دقيقة", "60-100 نبضة/دقيقة", "100-120 نبضة/دقيقة", "120-140 نبضة/دقيقة"],
        optionsEn: ["40-60 beats/min", "60-100 beats/min", "100-120 beats/min", "120-140 beats/min"],
        correct: 1, explanation: "المعدل الطبيعي لضربات القلب لدى البالغين هو 60-100 نبضة في الدقيقة.",
        explanationEn: "The normal heart rate for adults is 60-100 beats per minute.",
      },
      {
        id: "q1b", text: "أي مما يلي يعتبر أولوية عند تقييم مريض في حالة طوارئ؟",
        textEn: "Which of the following is a priority when assessing a patient in an emergency?",
        options: ["قياس درجة الحرارة", "تأمين مجرى الهواء (Airway)", "أخذ التاريخ المرضي", "قياس الوزن"],
        optionsEn: ["Measuring temperature", "Securing the airway", "Taking the medical history", "Measuring weight"],
        correct: 1, explanation: "وفق نهج ABC يأتي تأمين مجرى الهواء أولاً.",
        explanationEn: "According to the ABC approach, securing the airway comes first.",
      },
      {
        id: "q1c", text: "ما وضعية المريض المناسبة لتقليل ضيق التنفس؟",
        textEn: "Which patient position is appropriate to reduce shortness of breath?",
        options: ["وضعية الاستلقاء", "وضعية فاولر (Fowler)", "وضعية ترندلنبرغ", "الوضعية الجانبية"],
        optionsEn: ["Supine position", "Fowler's position", "Trendelenburg position", "Side-lying position"],
        correct: 1, explanation: "وضعية فاولر (الجلوس شبه المنتصب) تحسّن التنفس.",
        explanationEn: "Fowler's position (semi-upright sitting) improves breathing.",
      },
    ],
  },
  {
    id: "q2",
    title: "Prometric — علم الأدوية",
    titleEn: "Prometric — Pharmacology",
    description: "أسئلة على غرار امتحان بروميتريك في علم الأدوية والجرعات.",
    descriptionEn: "Prometric-style questions on pharmacology and dosing.",
    category: "Prometric",
    categoryEn: "Prometric",
    difficulty: "صعب",
    timeLimit: 8,
    passScore: 70,
    status: "published",
    demo: true,
    questions: [
      {
        id: "q2a", text: "أي فحص يُراقب مع مريض يتناول الوارفارين؟",
        textEn: "Which lab test is monitored for a patient taking warfarin?",
        options: ["مستوى السكر", "INR", "الهيموغلوبين", "البوتاسيوم"],
        optionsEn: ["Blood glucose level", "INR", "Hemoglobin", "Potassium"],
        correct: 1, explanation: "يُراقب INR لضبط جرعة الوارفارين.",
        explanationEn: "INR is monitored to adjust the warfarin dose.",
      },
      {
        id: "q2b", text: "الترياق (المضاد) لجرعة الهيبارين الزائدة هو؟",
        textEn: "The antidote for heparin overdose is?",
        options: ["فيتامين K", "بروتامين سلفات", "النالوكسون", "الأتروبين"],
        optionsEn: ["Vitamin K", "Protamine sulfate", "Naloxone", "Atropine"],
        correct: 1, explanation: "بروتامين سلفات هو الترياق للهيبارين.",
        explanationEn: "Protamine sulfate is the antidote for heparin.",
      },
    ],
  },
  {
    id: "q_med_calc",
    title: "حساب الجرعات الدوائية — تمرين تفاعلي",
    titleEn: "Medication Dose Calculations — Interactive Practice",
    description: "مسائل حسابية عملية: قواعد جرعة الطفل، معدل التنقيط والتسريب الوريدي، التخفيف، والجرعات المحسوبة على الوزن ومساحة سطح الجسم.",
    descriptionEn: "Practical calculation problems: pediatric dosing rules, IV drip and infusion rates, dilution, and weight- and body-surface-area-based dosing.",
    category: "حساب الجرعات",
    categoryEn: "Dose Calculation",
    difficulty: "متوسط",
    timeLimit: 20,
    passScore: 70,
    status: "published",
    demo: true,
    questions: [
      {
        id: "qmc1",
        text: "طفل عمره 6 سنوات، جرعة البالغ للدواء 500 مجم. احسبي جرعة الطفل باستخدام قاعدة Young (Age ÷ (Age+12) × جرعة البالغ).",
        textEn: "A 6-year-old child; the adult dose of the drug is 500 mg. Calculate the child's dose using Young's rule (Age ÷ (Age+12) × adult dose).",
        options: ["100 مجم", "167 مجم", "250 مجم", "300 مجم"],
        optionsEn: ["100 mg", "167 mg", "250 mg", "300 mg"],
        correct: 1, explanation: "6 ÷ (6+12) × 500 = 6/18 × 500 ≈ 167 مجم.",
        explanationEn: "6 ÷ (6+12) × 500 = 6/18 × 500 ≈ 167 mg.",
      },
      {
        id: "qmc2",
        text: "طفل وزنه 20 كجم، جرعة البالغ 300 مجم (بافتراض وزن بالغ قياسي 68 كجم). احسبي جرعة الطفل بقاعدة Clark (وزن الطفل ÷ وزن البالغ القياسي × جرعة البالغ).",
        textEn: "A child weighing 20 kg; the adult dose is 300 mg (assuming a standard adult weight of 68 kg). Calculate the child's dose using Clark's rule (child's weight ÷ standard adult weight × adult dose).",
        options: ["44 مجم", "88 مجم", "120 مجم", "150 مجم"],
        optionsEn: ["44 mg", "88 mg", "120 mg", "150 mg"],
        correct: 1, explanation: "20 ÷ 68 × 300 ≈ 88 مجم.",
        explanationEn: "20 ÷ 68 × 300 ≈ 88 mg.",
      },
      {
        id: "qmc3",
        text: "مريض وزنه 70 كجم، والجرعة الموصوفة 5 مجم/كجم. كم الجرعة الكلية المطلوبة؟",
        textEn: "A patient weighing 70 kg is prescribed 5 mg/kg. What is the total required dose?",
        options: ["70 مجم", "140 مجم", "350 مجم", "700 مجم"],
        optionsEn: ["70 mg", "140 mg", "350 mg", "700 mg"],
        correct: 2, explanation: "70 × 5 = 350 مجم.",
        explanationEn: "70 × 5 = 350 mg.",
      },
      {
        id: "qmc4",
        text: "لازم تُعطي 1000 مل محلول خلال 8 ساعات بمجموعة تسريب (drop factor) = 15 تنقيطة/مل. كم معدل التنقيط بالتنقيطة/دقيقة؟",
        textEn: "You must give 1000 mL of solution over 8 hours with an infusion set (drop factor) of 15 drops/mL. What is the drip rate in drops/minute?",
        options: ["21 تنقيطة/دقيقة", "31 تنقيطة/دقيقة", "42 تنقيطة/دقيقة", "63 تنقيطة/دقيقة"],
        optionsEn: ["21 drops/min", "31 drops/min", "42 drops/min", "63 drops/min"],
        correct: 1, explanation: "(1000 × 15) ÷ (8 × 60) = 15000 ÷ 480 ≈ 31 تنقيطة/دقيقة.",
        explanationEn: "(1000 × 15) ÷ (8 × 60) = 15000 ÷ 480 ≈ 31 drops/min.",
      },
      {
        id: "qmc5",
        text: "محلول 500 مل يُعطى خلال 4 ساعات عبر مضخة تسريب. كم معدل التسريب بالمل/ساعة؟",
        textEn: "A 500 mL solution is given over 4 hours via an infusion pump. What is the infusion rate in mL/hour?",
        options: ["100 مل/ساعة", "125 مل/ساعة", "150 مل/ساعة", "200 مل/ساعة"],
        optionsEn: ["100 mL/hr", "125 mL/hr", "150 mL/hr", "200 mL/hr"],
        correct: 1, explanation: "500 ÷ 4 = 125 مل/ساعة.",
        explanationEn: "500 ÷ 4 = 125 mL/hr.",
      },
      {
        id: "qmc6",
        text: "الطبيب طلب 0.25 مجم من دواء، والأمبولة المتاحة تركيزها 500 ميكروجرام/مل. كم مل ستسحبين؟",
        textEn: "The doctor ordered 0.25 mg of a drug, and the available ampule concentration is 500 micrograms/mL. How many mL will you draw up?",
        options: ["0.25 مل", "0.5 مل", "1 مل", "2 مل"],
        optionsEn: ["0.25 mL", "0.5 mL", "1 mL", "2 mL"],
        correct: 1, explanation: "0.25 مجم = 250 ميكروجرام؛ 250 ÷ 500 = 0.5 مل.",
        explanationEn: "0.25 mg = 250 micrograms; 250 ÷ 500 = 0.5 mL.",
      },
      {
        id: "qmc7",
        text: "أمبولة تركيزها 40 مجم/مل، ومطلوب تحضير 40 مل بتركيز 1 مجم/مل. كم مل من الأمبولة الأصلية تحتاجين (باستخدام C1V1=C2V2)؟",
        textEn: "An ampule has a concentration of 40 mg/mL, and you need to prepare 40 mL at a concentration of 1 mg/mL. How many mL of the original ampule do you need (using C1V1=C2V2)?",
        options: ["0.5 مل", "1 مل", "2 مل", "4 مل"],
        optionsEn: ["0.5 mL", "1 mL", "2 mL", "4 mL"],
        correct: 1, explanation: "40 × V1 = 1 × 40 → V1 = 1 مل.",
        explanationEn: "40 × V1 = 1 × 40 → V1 = 1 mL.",
      },
      {
        id: "qmc8",
        text: "المريض محتاج 24 وحدة إنسولين، والحقنة المدرّجة U-100 (1 مل = 100 وحدة). كم مل ستسحبين؟",
        textEn: "The patient needs 24 units of insulin, and the graduated syringe is U-100 (1 mL = 100 units). How many mL will you draw up?",
        options: ["0.12 مل", "0.24 مل", "0.4 مل", "2.4 مل"],
        optionsEn: ["0.12 mL", "0.24 mL", "0.4 mL", "2.4 mL"],
        correct: 1, explanation: "24 ÷ 100 = 0.24 مل.",
        explanationEn: "24 ÷ 100 = 0.24 mL.",
      },
      {
        id: "qmc9",
        text: "مساحة سطح جسم المريض 1.5 م²، والجرعة الموصوفة 100 مجم/م². كم الجرعة الكلية؟",
        textEn: "The patient's body surface area is 1.5 m², and the prescribed dose is 100 mg/m². What is the total dose?",
        options: ["100 مجم", "150 مجم", "175 مجم", "200 مجم"],
        optionsEn: ["100 mg", "150 mg", "175 mg", "200 mg"],
        correct: 1, explanation: "100 × 1.5 = 150 مجم.",
        explanationEn: "100 × 1.5 = 150 mg.",
      },
      {
        id: "qmc10",
        text: "الطبيب طلب إعطاء دواء دفعة وريدية (IV push) بمعدل 1 مل/دقيقة، والجرعة المطلوبة 4 مل. كم دقيقة سيستغرق الإعطاء الكامل؟",
        textEn: "The doctor ordered an IV push medication at a rate of 1 mL/minute, and the required dose is 4 mL. How many minutes will the full administration take?",
        options: ["1 دقيقة", "2 دقيقة", "4 دقائق", "8 دقائق"],
        optionsEn: ["1 minute", "2 minutes", "4 minutes", "8 minutes"],
        correct: 2, explanation: "4 مل ÷ 1 مل/دقيقة = 4 دقائق.",
        explanationEn: "4 mL ÷ 1 mL/minute = 4 minutes.",
      },
      {
        id: "qmc11",
        text: "بروتوكول الهيبارين يبدأ بجرعة تحميل 80 وحدة/كجم، لمريض وزنه 90 كجم. كم وحدة جرعة التحميل؟",
        textEn: "The heparin protocol starts with a loading dose of 80 units/kg, for a patient weighing 90 kg. How many units is the loading dose?",
        options: ["720 وحدة", "4500 وحدة", "7200 وحدة", "9000 وحدة"],
        optionsEn: ["720 units", "4500 units", "7200 units", "9000 units"],
        correct: 2, explanation: "80 × 90 = 7200 وحدة.",
        explanationEn: "80 × 90 = 7200 units.",
      },
      {
        id: "qmc12",
        text: "كم جرام دكستروز موجود في 500 مل من محلول دكستروز 5% (D5W)؟",
        textEn: "How many grams of dextrose are in 500 mL of 5% dextrose solution (D5W)?",
        options: ["5 جم", "25 جم", "50 جم", "100 جم"],
        optionsEn: ["5 g", "25 g", "50 g", "100 g"],
        correct: 1, explanation: "5% تعني 5 جم لكل 100 مل؛ 500 × 5 ÷ 100 = 25 جم.",
        explanationEn: "5% means 5 g per 100 mL; 500 × 5 ÷ 100 = 25 g.",
      },
      {
        id: "qmc13",
        text: "طفل وزنه 15 كجم، الحد الأقصى الآمن للدواء 40 مجم/كجم/يوم مقسومة كل 8 ساعات. الطبيب كتب 200 مجم كل 8 ساعات. هل الجرعة اليومية الكلية آمنة؟",
        textEn: "A child weighing 15 kg; the maximum safe dose of the drug is 40 mg/kg/day divided every 8 hours. The doctor prescribed 200 mg every 8 hours. Is the total daily dose safe?",
        options: ["آمنة ومطابقة تمامًا للحد الأقصى", "تتجاوز الحد الأقصى بالضعف", "أقل من اللازم بكثير", "تحتاج مضاعفة الجرعة"],
        optionsEn: ["Safe and exactly matches the maximum", "Exceeds the maximum by double", "Far below what is needed", "Needs the dose doubled"],
        correct: 0, explanation: "الحد الأقصى = 40 × 15 = 600 مجم/يوم. الجرعة الموصوفة = 200 × 3 = 600 مجم/يوم — مطابقة تمامًا للحد الأقصى.",
        explanationEn: "Maximum = 40 × 15 = 600 mg/day. Prescribed dose = 200 × 3 = 600 mg/day — exactly matches the maximum.",
      },
      {
        id: "qmc14",
        text: "معدل التسريب المطلوب 50 مل/ساعة، وحجم الكيس الكلي 1000 مل. كم ساعة سيستغرق تسريب الكيس بالكامل؟",
        textEn: "The required infusion rate is 50 mL/hour, and the total bag volume is 1000 mL. How many hours will it take to infuse the entire bag?",
        options: ["10 ساعات", "15 ساعة", "20 ساعة", "25 ساعة"],
        optionsEn: ["10 hours", "15 hours", "20 hours", "25 hours"],
        correct: 2, explanation: "1000 ÷ 50 = 20 ساعة.",
        explanationEn: "1000 ÷ 50 = 20 hours.",
      },
      {
        id: "qmc15",
        text: "أمبولة بودرة تحتوي 1 جم دواء، أُذيبت في 10 مل ماء للحقن. كم التركيز الناتج بالمجم/مل؟",
        textEn: "A powder ampule contains 1 g of drug, dissolved in 10 mL of water for injection. What is the resulting concentration in mg/mL?",
        options: ["10 مجم/مل", "50 مجم/مل", "100 مجم/مل", "1000 مجم/مل"],
        optionsEn: ["10 mg/mL", "50 mg/mL", "100 mg/mL", "1000 mg/mL"],
        correct: 2, explanation: "1 جم = 1000 مجم؛ 1000 ÷ 10 = 100 مجم/مل.",
        explanationEn: "1 g = 1000 mg; 1000 ÷ 10 = 100 mg/mL.",
      },
    ],
  },
];

export const seedCustomTypes: CustomType[] = [
  {
    id: "ct1",
    name: "دراسات حالة",
    slug: "case-studies",
    icon: "🏥",
    demo: true,
    fields: [
      { key: "patient", label: "بيانات المريض", type: "text" },
      { key: "presentation", label: "العرض السريري", type: "textarea" },
      { key: "management", label: "الخطة العلاجية", type: "textarea" },
    ],
  },
];
